### PR TITLE
[GCC][Warnings] SYSTEM includes and catch ref

### PR DESCRIPTION
**Pull request by moriarty**
This is an attempt to fix (silence) the buildbot failures from -Werror

@rctoris I didn't see the build error which the build farm complains about locally- but this would ignore warnings from system headers which we depend on.

### CODE REVIEW

**Comment by moriarty** [comment]
locally the only warming I get with this package is

```
/home/amoriarty/melodic-unique/src/robot_controllers/robot_controllers_interface/src/controller_loader.cpp:55:44: warning: catching polymorphic type ‘class pluginlib::LibraryLoadException’ by value [-Wcatch-value=]
     catch (pluginlib::LibraryLoadException e)
                                            ^
```

which is why I changed that line

**Comment by moriarty** [comment]
@rctoris I don't have access rights on this repo.

**Comment by erelson** [comment]
Fixed that for you

**Review by cjds — APPROVED** [review]
SRTM

**Pull request merged**
