### PR TITLE
update logging messages for galactic and later

### PR DESCRIPTION
**Pull request by mikeferguson**
https://docs.ros.org/en/humble/Releases/Release-Galactic-Geochelone.html#change-in-rclcpp-s-logging-macros

### CODE REVIEW

**Review by erelson — APPROVED** [review]

**Comment by erelson** [comment]
LGTM. Let me know if you want me to merge; but looks like you're able to do that. :+1:

**Comment by mikeferguson** [comment]
Yup, I'll merge - I just figured it was good to have at least a review

**Comment by mikeferguson** [comment]
I'm also going to do a release into humble later this week once I do some runtime testing

**Comment by erelson** [comment]
I appreciate knowing something changed! :)

**Pull request merged**
