### PR TITLE
Add initial support for ROS2

### PR DESCRIPTION
**Pull request by mikeferguson**

### CODE REVIEW

**Comment by mikeferguson** [comment]
@erelson this is all pretty well tested (on a UBR-1), I think we should probably merge this in, then setup CI before adding additional changes/fixes. See #46 for outstanding items (right now, biggest thing is that I haven't tested the gripper controller or scaled mimic -- but those are both really simple so I'm pretty sure they are nearly right). Also need to add some documentation, but figure I'll do that in a second PR that can be used to test the CI.

**Comment by mikeferguson** [comment]
Also, we should NOT do a squash merge - that will make it much easier for people to trace the changes.

**Comment by mikeferguson** [comment]
@erelson how about I merge this so I can do a first release and setup CI for foxy -- it will also make it possible to add some follow on PRs?

**Comment by erelson** [comment]
@mikeferguson sounds good to me. :+1:

**Review by erelson — APPROVED** [review]

**Pull request merged**
