### PR TITLE
add support for 4wd bases

### PR DESCRIPTION
**Pull request by mikeferguson**
This is a port of a ROS2 feature introduced in #53 to ROS1/noetic.

### CODE REVIEW

**Comment by mikeferguson** [comment]
@erelson I still need to test this out a bit more, but I opened the PR in case anyone had input.

**Comment by erelson** [comment]
@mikeferguson is this still in the works? Just checking, as I'll be doing a ros1 release this evening I think.

**Comment by mikeferguson** [comment]
@erelson this has been tested and should be ready to merge

**Review by erelson — APPROVED** [review]
Makes sense to me.

Musing: For a 4 wheel skid steer bot (ahh, FIRST robotics days, when I wasn't a coder), seems like wheel velocity as a function of desired spin-in-place rotation velocity would involve some math (external to this code) based on wheel positions relative to [center of robot]. :thinking:

**Comment by mikeferguson** [comment]
> Musing: For a 4 wheel skid steer bot (ahh, FIRST robotics days, when I wasn't a coder), seems like wheel velocity as a function of desired spin-in-place rotation velocity would involve some math (external to this code) based on wheel positions relative to [center of robot].

That already happens in the code as it is required for diff drive of any kind - but it only takes into account the Y offset (the X  offset, or forward-backward offset is basically neglected because your multiple wheels are acting like a virtual wheel at the centerline of the robot - and you have to scrub/skid off a bit as you rotate in place).

**Pull request merged**
