### PR TITLE
disable boost components of pluginlib

### PR DESCRIPTION
**Pull request by mikeferguson**

### CODE REVIEW

**Comment by mikeferguson** [comment]
@erelson I'm gonna open a PR against rosdistro to add PR testing for this repo (otherwise, this is gonna be tough to debug)

**Review by erelson — APPROVED** [review]
Looks right to me. Let's see if it builds!

**Comment by mikeferguson** [comment]
Yeah, I'm pretty sure this is the fix needed - what I'm not sure of is if I need to apply the same CMake patch to any other targets

**Comment by mikeferguson** [comment]
@erelson - I'd hold off on a new release yet - tests never ran here it looks like (although that means the merge tests SHOULD still run cause the buildfarm hasn't updated yet)

**Pull request merged**
